output "app_url" {
  description = "Public app URL. Uses Route53 domain when configured, otherwise the ALB DNS name."
  value       = "http://${local.route53_enabled ? local.domain_name : aws_lb.app.dns_name}"
}

output "domain_name" {
  description = "Route53 DNS name pointing to the ALB, or Route53 disabled when no domain is configured."
  value       = local.route53_enabled ? local.domain_name : "Route53 disabled"
}

output "alb_dns_name" {
  description = "DNS name of the public ALB."
  value       = aws_lb.app.dns_name
}

output "ec2_instance_id" {
  description = "EC2 instance running Docker and minikube."
  value       = aws_instance.minikube_host.id
}


output "ec2_public_ip" {
  description = "Public IP of the EC2 minikube host."
  value       = aws_instance.minikube_host.public_ip
}

output "ssh_private_key_path" {
  description = "Local private key generated by Terraform for EC2 SSH access."
  value       = local.ssh_key_path
}

output "ssh_command" {
  description = "SSH command for direct access to the EC2 minikube host."
  value       = "ssh -i ${local.ssh_key_path} ec2-user@${aws_instance.minikube_host.public_ip}"
}
